version: "3.8"
services:
  app:
    build: ./settings/php
    volumes:
      - ./main:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./main:/work
      - ./settings/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./settings/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: